import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import NavBar from "@/ui/navtopBar/NavBar";
// import { ReactQueryProvider } from "./react-query-provider";
const inter = Inter({ subsets: ["latin"] });
import FooterBar from "@/ui/Footer/FooterBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NavBar />

        <div className="containerA flex">
          <div className=" w-[10%]">hi</div>
          <main className="flex-1">{children}</main>
        </div>
        <footer className="fixed bottom-0 w-full bg-yellow-400 h-[10svh]">
          <FooterBar />
          <p>test </p>
        </footer>
      </body>
    </html>
  );
}
