import type { Metadata } from "next";
import NotFound from "./notfound";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <NotFound />
      </body>
    </html>
  );
}
